export const ACTION_TYPES = {
    ADD_ORDER: "ADD_ORDER",
    REMOVE_ORDER: "REMOVE_ORDER",
    INCREASE_QUANTITY: "INCREASE_QUANTITY",
    DECREASE_QUANTITY: "DECRASE_QUANTITY",
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_PRODUCT: "GET_PRODUCT",
    GET_PRODUCTS_CATEGORY: "GET_PRODUCTS_CATEGORY",
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_PRODUCT: "SET_PRODUCT",
    SET_PRODUCTS_CATEGORY: "SET_PRODUCTS_CATEGORY",
    ERROR_REQUEST: "ERROR_REQUEST"
}