export const ACTION_TYPES = {
    ADD_ORDER: "ADD_ORDER",
    REMOVE_ORDER: "REMOVE_ORDER",
    INCREASE_QUANTITY: "INCREASE_QUANTITY",
    DECREASE_QUANTITY: "DECRASE_QUANTITY",
    GET_PRODUCTS: "GET_PRODUCTS",
    SET_PRODUCTS: "SET_PRODUCTS",
    ERROR_REQUEST: "ERROR_REQUEST",
    SEND_EMAIL: "SEND_EMAIL",
    SEND_EMAIL_RESPONSE: "SEND_EMAIL_RESPONSE",
    SEND_EMAIL_ERROR: "SEND_EMAIL_ERROR",
    OPEN_REVIEW_WINDOW: "OPEN_REVIEW_WINDOW",
    CLOSE_REVIEW_WINDOW: "CLOSE_REVIEW_WINDOW",
    SEND_REVIEW: "SEND_REVIEW",
    SEND_REVIEW_SUCCESS: "SEND_REVIEW_SUCCESS",
    SEND_REVIEW_ERROR: "SEND_REVIEW_ERROR"
}