export const ACTION_TYPES = {
    ADD_ORDER: "ADD_ORDER",
    REMOVE_ORDER: "REMOVE_ORDER",
    INCREASE_QUANTITY: "INCREASE_QUANTITY",
    DECREASE_QUANTITY: "DECRASE_QUANTITY",
    GET_PRODUCTS: "GET_PRODUCTS",
    SET_PRODUCTS: "SET_PRODUCTS",
    ERROR_REQUEST: "ERROR_REQUEST"
}